name: build-caddyfile-users

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "caddy.Dockerfile"
      - ".github/workflows/build-caddy.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "caddy-file-generator.Dockerfile"
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/caddyfile-generator:latest
          platforms: linux/amd64,linux/arm64
